project:
  name: local

#DB Configuration:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: demo
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: